version: "3.7"
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:12.6
    environment:
      POSTGRES_DB: "test-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command: ["postgres", "-c", "log_statement=all"]